# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters:
    # Configuration pour les posts
    app.posts.default_limit: 10
    app.posts.max_limit: 50

    # Configuration pour l'upload d'images
    app.uploads.max_size: "2M"
    app.uploads.allowed_extensions:
        - "jpg"
        - "jpeg"
        - "png"
        - "webp"
        - "avif"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # === Configuration des Services SOLID ===

    # Interface Bindings - Respecte le principe DIP (Dependency Inversion)
    App\Contract\ValidatorInterface: '@App\Service\EntityValidationService'
    App\Contract\DataFormatterInterface: '@App\Service\ApiDataFormatterService'
    App\Contract\ChatManagementInterface: '@App\Service\ChatManagementService'
    App\Contract\PersistenceInterface: '@App\Service\DoctrinePersistenceService'

    # Services spécialisés - Respectent le principe SRP (Single Responsibility)
    App\Service\EntityValidationService: ~
    App\Service\ApiDataFormatterService: ~
    App\Service\ChatManagementService: ~
    App\Service\DoctrinePersistenceService: ~

    # Configuration du PostService avec ses nouvelles dépendances
    App\Service\PostService:
        arguments:
            $defaultLimit: "%app.posts.default_limit%"
            $persistenceService: '@App\Contract\PersistenceInterface'
            $validationService: '@App\Contract\ValidatorInterface'
